### ISSUE TITLE
Installation fails on arch linux

### ISSUE THREAD

**Issue by bf** [ibc/mediasoup#82] opened 2017-03-29 18:39 UTC
When installing on my arch linux system with both python2 and python3 installed, I get the following error:

```
bf@xxx> npm i --save mediasoup 

> mediasoup@0.8.0 postinstall /foo/bar/node_modules/mediasoup
> make Release

cd worker &&  ./scripts/configure.py -R mediasoup-worker
  File "./scripts/configure.py", line 48
    print 'Error running GYP'
                            ^
SyntaxError: Missing parentheses in call to 'print'
make: *** [Makefile:19: Release] Error 1
```

It looks like `PYTHON?=$(type -p python2 || echo python)` in `Makefile` returns an empty string. When I do `type -p python2 || echo python` in bash it returns `/usr/bin/python2`. The shell from which I am using npm is fish.

Can anybody help me?

**Comment by ibc** [comment] 2017-03-29 19:06
Interesting. No idea about `fish`, but I've installed it to check and indeed the problem is there:

```bash
ibc@ibc-macbook ~> echo $(type -p python2 || echo python)
Unsupported use of '||'. In fish, please use 'COMMAND; or COMMAND'.
fish: echo $(type -p python2 || echo python)
                              ^
```

@saghul help please :)

**Comment by ibc** [comment] 2017-03-29 19:10
To be clear: using `or` instead of `||` would not work in bash/sh, so that's not a solution.

**Comment by bf** [comment] 2017-03-29 19:18
@ibc how about we add a `#!/bin/bash` on top of the Makefile? Would it then run in bash?

**Comment by ibc** [comment] 2017-03-29 19:20
No, Makefiles are not scripts but just text files read and interpreted by the `make` command.

**Comment by ibc** [comment] 2017-03-29 19:21
@bf I don't know how to solve it right now. In the meanwhile, may you try moving to bash or sh before `npm install mediasoup`?

**Comment by ibc** [comment] 2017-03-29 19:30
Just asked in [StackOverflow](https://stackoverflow.com/questions/43102552/same-fish-and-bash-command-for-detecting-python-executable-name), let's see.

**Comment by bf** [comment] 2017-03-29 19:30
@ibc you're right. I shouldn't worry about this because the servers aren't running this weird shell :-) They run plain bash. I'll try installing within bash on my dev machine.

Thanks also for your immediate response, much appreciated. Keep up the good work. Will post again to let you know if it worked.

**Comment by bf** [comment] 2017-03-29 19:34
@ibc Dang. I tried in `bash` and `sh`, both return the same error. I also did `su root` and npm install there, also same error. I tried `sudo -u foo npm i --save ...` but it didn't work because of missing `nvm` initialization.

Not sure what I can do?

**Comment by ibc** [comment] 2017-03-29 19:38
I'm pretty sure it cannot be the same error.  Please try a fresh install with your user (don't use root), using bash, and ensure you have all the [requirements](https://github.com/ibc/mediasoup#installation).

Also, before it, run `npm cache clean`.

**Comment by bf** [comment] 2017-03-29 19:43
```
[2]> bash
[foo@archibald bar]$ npm install --save mediasoup

> mediasoup@0.8.0 postinstall /home/foo/src/bar/node_modules/mediasoup
> make Release

cd worker &&  ./scripts/configure.py -R mediasoup-worker
  File "./scripts/configure.py", line 48
    print 'Error running GYP'
                            ^
SyntaxError: Missing parentheses in call to 'print'
make: *** [Makefile:19: Release] Error 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN mummy@3.0.2 requires a peer of hapi@^13.0.0 but none was installed.
npm ERR! Linux 4.10.4-1-ARCH
npm ERR! argv "/home/foo/.nvm/versions/node/v6.9.1/bin/node" "/home/foo/.nvm/versions/node/v6.9.1/bin/npm" "install" "--save" "mediasoup"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! mediasoup@0.8.0 postinstall: `make Release`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the mediasoup@0.8.0 postinstall script 'make Release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mediasoup package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make Release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mediasoup
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mediasoup
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/foo/src/bar/npm-debug.log
[foo@archibald bar]$ exit
exit
foo@archibald ~/s/bar (master) [1]> sh
sh-4.4$ npm install --save mediasoup

> mediasoup@0.8.0 postinstall /home/foo/src/bar/node_modules/mediasoup
> make Release

cd worker &&  ./scripts/configure.py -R mediasoup-worker
  File "./scripts/configure.py", line 48
    print 'Error running GYP'
                            ^
SyntaxError: Missing parentheses in call to 'print'
make: *** [Makefile:19: Release] Error 1
[                ..] \ postinstall: info lifecycle mediasoup@0.8.0~postinstall: Failed


^C               ..] \ postinstall: info lifecycle mediasoup@0.8.0~postinstall: Failed



sh-4.4$ exit
foo@archibald ~/s/bar (master) [130]> su root
Password: 
[root@archibald bar]# sudo -u foo -s /bin/bash npm i --save mediasoup 
/home/foo/.nvm/versions/node/v6.9.1/bin/npm: npm: line 2: syntax error near unexpected token `;'
/home/foo/.nvm/versions/node/v6.9.1/bin/npm: npm: line 2: `;(function () { // wrapper in case we're in module_context mode'
[root@archibald bar]# ^C
[root@archibald bar]# npm i --save mediasoup

> mediasoup@0.8.0 postinstall /home/foo/src/bar/node_modules/mediasoup
> make Release

cd worker &&  ./scripts/configure.py -R mediasoup-worker
  File "./scripts/configure.py", line 48
    print 'Error running GYP'
                            ^
SyntaxError: Missing parentheses in call to 'print'
make: *** [Makefile:19: Release] Error 1

[root@archibald bar]# 
[root@archibald bar]# ^C
[root@archibald bar]# gre^C
[root@archibald bar]# exit
```

**Comment by ibc** [comment] 2017-03-29 19:50
Instead, in my computer (in which fish is not my default bash) it works even if I run `npm install mediasoup` within a fish shell. Which clearly tells me that `make` runs a shell internally (the default shell?).

**Comment by ibc** [comment] 2017-03-29 19:53
https://www.gnu.org/software/make/manual/html_node/Choosing-the-Shell.html

> The program used as the shell is taken from the variable SHELL. If this variable is not set in your makefile, the program /bin/sh is used as the shell.

**Comment by ibc** [comment] 2017-03-29 19:54
So try this:

```bash
SHELL=/bin/bash  npm install mediasoup
```

**Comment by ibc** [comment] 2017-03-29 19:56
If it fails, please clone the source code, open the Makefile in the root directory and add this at the top:

```
SHELL := /bin/bash
```

Then run `make` and let's see.

**Comment by bf** [comment] 2017-03-29 19:57
```
env SHELL=/bin/bash  npm install mediasoup --save

> mediasoup@0.8.0 postinstall /home/beni/src/strivewire/node_modules/mediasoup
> make Release

cd worker &&  ./scripts/configure.py -R mediasoup-worker
```

**Comment by bf** [comment] 2017-03-29 19:57
I'll clone the repo :)

**Comment by ibc** [comment] 2017-03-29 19:57
more info: http://stackoverflow.com/questions/589276/how-can-i-use-bash-syntax-in-makefile-targets

**Comment by bf** [comment] 2017-03-29 20:06
```> whereis python2
python2: /usr/bin/python2 /usr/bin/python2.7-config /usr/bin/python2.7 /usr/lib/python2.7 /usr/local/lib/python2.7 /usr/include/python2.7 /usr/share/man/man1/python2.1.gz```

Sorry to bother you with this weird bug.

**Comment by ibc** [comment] 2017-03-29 20:08
Please, upgrade your `master` branch repo and try again (I'll reopen the issue until confirmed).

**Comment by bf** [comment] 2017-03-29 20:09
Tested the new master, receive a gyp error.


```
> make
make Release
make[1]: Entering directory '/tmp/mediasoup'
cd worker &&  ./scripts/configure.py -R mediasoup-worker
Traceback (most recent call last):
  File "./scripts/configure.py", line 13, in <module>
    raise RuntimeError('gyp requires Python 2, but this is Python ' + str(version) + ', ensure your python2 or python command points to the Python 2 executable')
RuntimeError: gyp requires Python 2, but this is Python 3, ensure your python2 or python command points to the Python 2 executable
make[1]: *** [Makefile:19: Release] Error 1
make[1]: Leaving directory '/tmp/mediasoup'
make: *** [Makefile:15: default] Error 2
```

**Comment by ibc** [comment] 2017-03-29 20:13
I'm a bit lost... don't you have `python2` executable? Please, enter into a bash session and run:

```bash
$ python2 -V

$ python -V

$ echo $(type -p python2 || echo python)
```

**Comment by bf** [comment] 2017-03-29 20:15
```[beni@archibald strivewire]$ python2 -V
Python 2.7.13
[beni@archibald strivewire]$ python -V
Python 3.6.0
[beni@archibald strivewire]$ echo $(type -p python2 || echo python)
/usr/bin/python2
[beni@archibald strivewire]$ whereis python2
python2: /usr/bin/python2 /usr/bin/python2.7-config /usr/bin/python2.7 /usr/lib/python2.7 /usr/local/lib/python2.7 /usr/include/python2.7 /usr/share/man/man1/python2.1.gz
[beni@archibald strivewire]$ 
```

**Comment by bf** [comment] 2017-03-29 20:18
maybe we can learn from another python detection approach?

https://github.com/rabbitmq/rabbitmq-server/pull/213/commits/383b70bb4e643f0dfb7d79c3ee841819dc0a0ff3

**Comment by bf** [comment] 2017-03-29 20:22
I mean it is most likely the `?=` in the Makefile line `PYTHON?=`. My default python is 3, but I also have python 2 installed, available via `python2` and `python2.7`. What should we do?

**Comment by ibc** [comment] 2017-03-29 20:30
We are missing something, it does not make sense. Please do this:

```bash
$ bash

$ python2 -V

$ python -V

$ which python2

$ which python

$ echo $(type -p python2 || echo python)

$ echo $PATH
```


```bash
$ sh

$ python2 -V

$ python -V

$ which python2

$ which python

$ echo $(type -p python2 || echo python)

$ echo $PATH
```

**Comment by bf** [comment] 2017-03-29 20:40
Here you are: 

```
$ python2 -V
Python 2.7.13
[beni@archibald mediasoup]$ python -V
Python 3.6.0
[beni@archibald mediasoup]$ which python2
/usr/bin/python2
[beni@archibald mediasoup]$ which python
/usr/bin/python
[beni@archibald mediasoup]$ echo $(type -p python2 || echo python)
/usr/bin/python2
[beni@archibald mediasoup]$ echo $PATH
/home/beni/.nvm/versions/node/v6.9.1/bin:/home/beni/.gem/ruby/2.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
[beni@archibald mediasoup]$ echo $PYTHON

[beni@archibald mediasoup]$ sh
sh-4.4$ python2 -V
Python 2.7.13
sh-4.4$ python -V
Python 3.6.0
sh-4.4$ which python2
/usr/bin/python2
sh-4.4$ which python
/usr/bin/python
sh-4.4$ echo $(type -p python2 || echo python)
/usr/bin/python2
sh-4.4$ echo $PATH
/home/beni/.nvm/versions/node/v6.9.1/bin:/home/beni/.gem/ruby/2.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
sh-4.4$ echo $PYTHON

sh-4.4$ 

```

**Comment by ibc** [comment] 2017-03-29 20:50
This is crazy. Please edit Makefile as follows:

```
default:
	@echo $(shell python -V 2>&1)
ifeq ($(MEDIASOUP_BUILDTYPE),Debug)
	make Debug
else
	make Release
endif
```

and run make again.

**Comment by ibc** [comment] 2017-03-29 20:52
Also add this:

```
  @echo PYTHON: ${PYTHON}
```

**Comment by bf** [comment] 2017-03-29 20:54
I changed `@echo PYTHON: ${PYTHON}` to `@echo PYTHON: AAA${PYTHON}BBB`:

```
> make
Python 3.6.0
PYTHON: AAABBB
make Release
make[1]: Entering directory '/tmp/mediasoup'
```

**Comment by bf** [comment] 2017-03-29 20:55
Please see the following from http://stackoverflow.com/a/448973/282259

`Using ?= assigns the variable a value iff the variable was not previously assigned. If the variable was previously assigned a blank value (VAR=), it is still considered set I think. Otherwise, functions exactly like =.`

It is most likely the ?= operator!

**Comment by bf** [comment] 2017-03-29 20:56
Also see section about ?= in https://www.gnu.org/software/make/manual/make.html#Reading-Makefiles it says the same. Empty variable != Undefined variable in makefile it seems.

**Comment by bf** [comment] 2017-03-29 20:58
Yes that is what it is! See:

```
default:
        @echo $(shell python -V 2>&1)
        @echo PYTHON: AAA${PYTHON}BBB
        @echo $(origin FOO)
        @echo $(origin PYTHON)
```



```
> make
Python 3.6.0
PYTHON: AAABBB
undefined
file
make Release
```

**Comment by ibc** [comment] 2017-03-29 20:59
Still I don't understand why `PYTHON` was **already** set (to an empty string).

**Comment by bf** [comment] 2017-03-29 20:59
According to https://stackoverflow.com/questions/38801796/makefile-set-if-variable-is-empty we should use 
```
ifeq ($(PYTHON),)
PYTHON := $(type -p python2 || echo python)
endif
```

and be happy

**Comment by bf** [comment] 2017-03-29 21:00
It seems to be a rather common bug with Makefiles?

**Comment by ibc** [comment] 2017-03-29 21:00
Yep, but still I don't know why `PYTHON` already has a value in your case.

**Comment by ibc** [comment] 2017-03-29 21:03
Thanks, let's move the conversation to your PR #83.

**Comment by ibc** [comment] 2017-03-29 21:12
I'm completely lost right now. I even think that the line `PYTHON?=$(type -p python2 || echo python)` did never work before.

In fact, if I remove it and run `make`, it **works**! how is possible?

**Comment by bf** [comment] 2017-03-29 21:15
If I remove the line it still doesnt work because my `python` is 3  ;) 

I really, really appreciate your help this evening. Thank you.

**Comment by ibc** [comment] 2017-03-29 21:17
mmm, I think I got it!

Please, try just this:

```
PYTHON := $(shell type -p python2 || echo python)
```

**Comment by bf** [comment] 2017-03-29 21:26
This works! Nice!

**Comment by ibc** [comment] 2017-03-29 21:27
wow! finally! I hate Python and Makefiles... XD

**Comment by ibc** [comment] 2017-03-29 21:27
Thanks a lot for your report and contribution. We fixed a real bug!

**Comment by bf** [comment] 2017-03-29 21:28
Now I can also tell a real story why I hate Makefiles :D

**Comment by ibc** [comment] 2017-03-29 21:35
OMG... https://travis-ci.org/ibc/mediasoup/jobs/216524554

Well, I'll check it tomorrow...

**Comment by bf** [comment] 2017-03-29 21:36
This is the prime example of management asking "what did you do yesterday?" - "oh there was this edge case...".....

Thanks again and good night.

**Closed** 2017-03-29 21:55 UTC

**Comment by funnywwh** [comment] 2019-10-11 08:50
> [2]> bash
> [foo@archibald bar]$ npm install --save mediasoup
> 
> > mediasoup@0.8.0 postinstall /home/foo/src/bar/node_modules/mediasoup
> > make Release
> 
> cd worker &&  ./scripts/configure.py -R mediasoup-worker
>   File "./scripts/configure.py", line 48
>     print 'Error running GYP'
>                             ^
> SyntaxError: Missing parentheses in call to 'print'
> make: *** [Makefile:19: Release] Error 1
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN mummy@3.0.2 requires a peer of hapi@^13.0.0 but none was installed.
> npm ERR! Linux 4.10.4-1-ARCH
> npm ERR! argv "/home/foo/.nvm/versions/node/v6.9.1/bin/node" "/home/foo/.nvm/versions/node/v6.9.1/bin/npm" "install" "--save" "mediasoup"
> npm ERR! node v6.9.1
> npm ERR! npm  v3.10.8
> npm ERR! code ELIFECYCLE
> 
> npm ERR! mediasoup@0.8.0 postinstall: `make Release`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the mediasoup@0.8.0 postinstall script 'make Release'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the mediasoup package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     make Release
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs mediasoup
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls mediasoup
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/foo/src/bar/npm-debug.log
> [foo@archibald bar]$ exit
> exit
> foo@archibald ~/s/bar (master) [1]> sh
> sh-4.4$ npm install --save mediasoup
> 
> > mediasoup@0.8.0 postinstall /home/foo/src/bar/node_modules/mediasoup
> > make Release
> 
> cd worker &&  ./scripts/configure.py -R mediasoup-worker
>   File "./scripts/configure.py", line 48
>     print 'Error running GYP'
>                             ^
> SyntaxError: Missing parentheses in call to 'print'
> make: *** [Makefile:19: Release] Error 1
> [                ..] \ postinstall: info lifecycle mediasoup@0.8.0~postinstall: Failed
> 
> 
> ^C               ..] \ postinstall: info lifecycle mediasoup@0.8.0~postinstall: Failed
> 
> 
> 
> sh-4.4$ exit
> foo@archibald ~/s/bar (master) [130]> su root
> Password: 
> [root@archibald bar]# sudo -u foo -s /bin/bash npm i --save mediasoup 
> /home/foo/.nvm/versions/node/v6.9.1/bin/npm: npm: line 2: syntax error near unexpected token `;'
> /home/foo/.nvm/versions/node/v6.9.1/bin/npm: npm: line 2: `;(function () { // wrapper in case we're in module_context mode'
> [root@archibald bar]# ^C
> [root@archibald bar]# npm i --save mediasoup
> 
> > mediasoup@0.8.0 postinstall /home/foo/src/bar/node_modules/mediasoup
> > make Release
> 
> cd worker &&  ./scripts/configure.py -R mediasoup-worker
>   File "./scripts/configure.py", line 48
>     print 'Error running GYP'
>                             ^
> SyntaxError: Missing parentheses in call to 'print'
> make: *** [Makefile:19: Release] Error 1
> 
> [root@archibald bar]# 
> [root@archibald bar]# ^C
> [root@archibald bar]# gre^C
> [root@archibald bar]# exit

Is it solved?

**Comment by ibc** [comment] 2019-10-11 08:52
`mediasoup@0.8.0`?

Sorry, no support for that super old version.

**Comment by funnywwh** [comment] 2019-10-11 09:03
> `mediasoup@0.8.0`?
> 
> Sorry, no support for that super old version.

my version is 3

**Comment by ibc** [comment] 2019-10-11 09:04
I'm afraid it's `mediasoup@0.8.0` as clearly shown  in the log above. Please check that.

**Comment by funnywwh** [comment] 2019-10-11 09:06
root@winger:~/mediasoup/mediasoup-demo/server# npm i --save mediasoup

> clang-tools-prebuilt@0.1.4 postinstall /root/mediasoup/mediasoup-demo/server/node_modules/clang-tools-prebuilt
> node install.js

sh: 1: node: Permission denied

> mediasoup@3.2.5 postinstall /root/mediasoup/mediasoup-demo/server/node_modules/mediasoup
> make -C worker

make: Entering directory '/root/mediasoup/mediasoup-demo/server/node_modules/mediasoup/worker'
/usr/bin/python2 ./scripts/configure.py -R mediasoup-worker
['-R', 'mediasoup-worker', '/root/mediasoup/mediasoup-demo/server/node_modules/mediasoup/worker/mediasoup-worker.gyp', '--depth=.', '-f', 'make', '-Goutput_dir=/root/mediasoup/mediasoup-demo/server/node_modules/mediasoup/worker/out', '--generator-output', '/root/mediasoup/mediasoup-demo/server/node_modules/mediasoup/worker/out', '-Dgcc_version=54', '-Dclang=0', '-Dhost_arch=x64', '-Dtarget_arch=x64', '-Dopenssl_fips=', '-Dmediasoup_asan=false', '-Dnode_byteorder=little']
gyp: /root/mediasoup/mediasoup-demo/server/node_modules/mediasoup/worker/mediasoup-worker.gyp not found (cwd: /root/mediasoup/mediasoup-demo/server/node_modules/mediasoup/worker)
Makefile:22: recipe for target 'default' failed
make: *** [default] Error 1
make: Leaving directory '/root/mediasoup/mediasoup-demo/server/node_modules/mediasoup/worker'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: clang-tools-prebuilt@0.1.4 (node_modules/clang-tools-prebuilt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: clang-tools-prebuilt@0.1.4 postinstall: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn ENOENT

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mediasoup@3.2.5 postinstall: `make -C worker`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mediasoup@3.2.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-11T08_21_57_789Z-debug.log

**Comment by ibc** [comment] 2019-10-11 09:09
We wrote documentation for something: https://mediasoup.org/documentation/v3/mediasoup/installation/#linux-osx-and-any-nix-system
